name: Pull request

on:
  pull_request:
    branches:
      - master
  workflow_dispatch: { }

jobs:

  docker-build-test:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      DOCKER_IMAGE: dataeng
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        id: gcp_auth
        with:
          credentials_json: ${{ secrets.GCP_VNOC_DEV_SA_JSON_BASE64 }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        
      - name: Register gcloud as a Docker credential helper
        run: gcloud auth configure-docker europe-north1-docker.pkg.dev

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          architecture: x64

      - name: Create version.json
        run: make version.json

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Define image meta
        id: docker_meta
        uses: docker/metadata-action@v4
        with:
          images: |
            europe-north1-docker.pkg.dev/vivid-env-450617-g5/teemu-images/${{ env.DOCKER_IMAGE }}
          flavor: |
            latest=false
          tags: |
            type=raw,value=tmp
          labels: |
            org.opencontainers.image.authors=teemu1
            org.opencontainers.image.vendor=teemu

      - name: Build release image
        uses: docker/build-push-action@v4
        with:
          context: .
          no-cache: false
          push: false
          platforms: linux/amd64
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          provenance: false
          secret-files: |
            gcp_secret=${{ steps.gcp_auth.outputs.credentials_file_path }}
